.\" Man page for DailyDesktopWallpaperPlus
.\" Contact: patrice.coni-dev@yandex.com
.TH UltimateDailyWallpaper 1 "January  29 2023"
.SH NAME
UltimateDailyWallpaper \- Wallpaper changer and automatic wallpaper downloader
.SH SYNOPSIS
.B UltimateDailyWallpaper
.SH DESCRIPTION
UltimateDailyWallpaper is a utility to set the daily picture as
wallpaper from a selected provider. It saves pictures in a high quality.
Further information about each picture can be obtained from the
Internet with a single click. It integrates with most desktop
environments to provide automatically changing wallpaper. It
allows a simple integration of plugins, which allows downloading
a daily wallpaper from any one provider.

Default directory for plugins: /usr/lib/UltimateDailyWallpaper-plugins
.SH OPTIONS
No options for this man pages.
.SH SEE ALSO
man(1), groff(1), man.config(5)
.SH BUGS
If you find a bug, please report it at below E-Mail-address.
.SH AUTHOR
Patrice Coni (patrice.coni-dev@yandex.com)
