.\" Man page for DailyDesktopWallpaperPlus
.\" Contact: patrice.coni-dev@yandex.com
.TH UltimateDailyWallpaper 1 "December  24 2022"
.SH NAME
UltimateDailyWallpaper \- A wallpaper changer
.SH SYNOPSIS
UltimateDailyWallpaper - Daily image as wallpaper of a selected provider.
.SH DESCRIPTION
UltimateDailyWallpaper is a utility to set the Wikimedia Commons 
daily picture as wallpaper. It saves pictures in a high quality. 
Further information about each picture can be obtained from the 
Internet with a single click. It integrates with most X11 desktop 
environments to provide automatically changing wallpaper.
.SH OPTIONS
No options for this man pages.
.SH SEE ALSO
man(1), groff(1), man.config(5)
.SH BUGS
If you find a bug, please report it at below E-Mail-address.
.SH AUTHOR
Patrice Coni (patrice.coni-dev@yandex.com)
